CREATE TABLE USER_DETAILS(
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(40),
	ROLE_NAME VARCHAR(30),
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	EMAIL VARCHAR(70),
	CREATED_DATE DATETIME
);

INSERT INTO USER_DETAILS (USERNAME,PASSWORD,ROLE_NAME,FIRST_NAME,LAST_NAME,EMAIL) VALUES ('admin','admin','admin','admin','admin','admin@dmodi.com');
INSERT INTO USER_DETAILS (USERNAME,PASSWORD,ROLE_NAME,FIRST_NAME,LAST_NAME,EMAIL) VALUES ('dmodi','dmodi','ops_user','dmodi','dmodi','dmodi@dmodi.com');
